### ISSUE TITLE
Can the Gem Push workflow use a supported Ruby version?

### ISSUE THREAD

**Issue by aramprice** [cloudfoundry/omniauth-uaa-oauth2#29]
The [gem-push.yml](https://github.com/cloudfoundry/omniauth-uaa-oauth2/blob/master/.github/workflows/gem-push.yml#L13-L18) workflow appears to use Ruby 2.6 which has been [out of support for ~4 years](https://endoflife.date/ruby)

```yaml
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
```

Can this action be updated to consume a supported Ruby version?
